"""Emit WorldEditorRemix Python scripts -- the interactive, undoable edit path.

Two ways to change a map. Writing bytes is right for bulk, mechanical,
whole-sector work. Driving the editor is right when the user wants to *see* the
change and undo it: the editor gives real rendering, real collision preview and
a working undo stack that a byte rewrite cannot.

**The API is not uniformly safe.** Verified against the C++ in
``PythonWorldEditorModule.cpp``; the traps below are why this module wraps a
deliberately small subset rather than exposing all 281 bindings:

* ``SetAttrAt`` / ``DrawAttrBrush`` pass world centimetres where
  ``CTerrainAccessor::DrawAttrBrush`` expects terrain-LOCAL cells 0..127. They
  do not do what their names say. Use ``SetAttrAtWorld``.
* ``GetAttrAt`` / ``IsAttrOn`` read world cm with POSITIVE y;
  ``SetAttrAtWorld`` uses a different convention. Getter and setter are not
  symmetric.
* ``DrawHeightBrush`` discards the sector argument entirely -- it calls
  ``GetEditTerrain()`` and paints the *current* edit terrain wherever you aimed.
* Only a **3x3 sector window** is addressable at a time (``AROUND_AREA_NUM 9``).
  A script that walks a 6x6 map without moving the camera silently edits nothing
  outside the loaded window.

So the emitted scripts move the camera per sector, prefer the world-space
setters, and never use the three broken entry points.
"""

from __future__ import annotations

from typing import Iterable, List, Optional, Sequence, Tuple

from ..codec import areadata as ad

HEADER = '''\
# Generated by m2map. Run inside WorldEditorRemix (Python 3.9 host).
#
# Safety notes baked into this script -- do not "simplify" them away:
#   * SetAttrAt / DrawAttrBrush take terrain-LOCAL cells, not world cm, and are
#     therefore avoided entirely. SetAttrAtWorld is used instead.
#   * DrawHeightBrush ignores the sector you pass and edits the CURRENT edit
#     terrain, so the camera is moved before each sector is touched.
#   * Only a 3x3 sector window is addressable; edits outside it are dropped
#     silently.
import WorldEditor as we
import dbg


def _log(msg):
    dbg.Tracen("[m2map] " + str(msg))


def _require_map():
    if not we.IsMapReady():
        raise RuntimeError("no map is open in the editor")
'''

FOOTER = '''

if __name__ == "__main__":
    main()
'''


def _fmt(v: float) -> str:
    return "%.6f" % v


def insert_objects(records: Sequence[ad.ObjectRecord], label: str = "objects") -> str:
    """A script that inserts placements, moving the camera per sector.

    Coordinates in ``areadata`` are map-local with Y negated; the editor's
    world-space calls want de-negated Y, so the conversion happens here once
    rather than in the caller.
    """
    by_sector = {}
    for r in records:
        key = (int(r.x // 25600), int((-r.y) // 25600))
        by_sector.setdefault(key, []).append(r)

    lines: List[str] = [HEADER, "", "", "def main():", "    _require_map()",
                        "    placed = 0"]
    for (cx, cy), recs in sorted(by_sector.items()):
        lines.append("")
        lines.append("    # --- sector %03d%03d (%d objects) ---" % (cx, cy, len(recs)))
        # Centre the 3x3 window on this sector before touching it.
        lines.append("    we.UpdateTargetPosition(%d, %d)"
                     % (cx * 25600 + 12800, cy * 25600 + 12800))
        lines.append("    we.PreloadTerrainAndArea(%d, %d)" % (cx, cy))
        for r in recs:
            lines.append("    we.InsertObject(%s, %s, %s, %d)  # roll %.0f"
                         % (_fmt(r.x), _fmt(-r.y), _fmt(r.z), r.crc, r.roll))
            if r.roll:
                lines.append("    we.SetObjectRotation(we.GetLastPickedAreaIndex(), "
                             "%s, %s, %s)" % (_fmt(r.yaw), _fmt(r.pitch), _fmt(r.roll)))
            if r.height_bias:
                lines.append("    we.SetObjectHeightBias(we.GetLastPickedAreaIndex(), %s)"
                             % _fmt(r.height_bias))
            lines.append("    placed += 1")

    lines += ["", "    we.RefreshSelectedInfo()",
              "    we.SaveAreas()",
              '    _log("%s: inserted %%d objects" %% placed)' % label,
              FOOTER]
    return "\n".join(lines)


def replace_crc(pairs: Iterable[Tuple[int, int]], scope: int = 1) -> str:
    """Swap one property CRC for another across the map -- the reskin primitive.

    ``ReplaceObjectsByCRC`` is one of the few bulk operations the editor exposes
    that is both verified and safe, and it keeps the undo stack intact.
    """
    lines = [HEADER, "", "", "def main():", "    _require_map()"]
    for old, new in pairs:
        lines.append("    we.ReplaceObjectsByCRC(%d, %d, %d)" % (old, new, scope))
        lines.append('    _log("replaced %d -> %d")' % (old, new))
    lines += ["", "    we.SaveAreas()", FOOTER]
    return "\n".join(lines)


def delete_crcs(crcs: Sequence[int], scope: int = 1) -> str:
    lines = [HEADER, "", "", "def main():", "    _require_map()",
             "    we.DeleteObjectsByCRCList([%s], %d)"
             % (", ".join(str(int(c)) for c in crcs), scope),
             '    _log("deleted %d CRC(s)")' % len(crcs),
             "    we.SaveAreas()", FOOTER]
    return "\n".join(lines)


def set_attr_region(cells: Sequence[Tuple[float, float]], flag: int,
                    erase: bool = False) -> str:
    """Set or clear an attribute flag at world positions.

    Uses ``SetAttrAtWorld`` deliberately: ``SetAttrAt`` and ``DrawAttrBrush``
    pass world centimetres into a function expecting terrain-local cells 0..127,
    so they write to the wrong place with no error.
    """
    lines = [HEADER, "", "", "def main():", "    _require_map()",
             "    we.SetEraseAttr(%d)" % (1 if erase else 0)]
    for x, y in cells:
        lines.append("    we.SetAttrAtWorld(%s, %s, %d)" % (_fmt(x), _fmt(y), flag))
    lines += ["    we.SetEraseAttr(0)",
              "    we.RefreshAllTerrainAttrs()",
              "    we.GenerateServerAttr()",
              '    _log("attr updated at %d position(s)")' % len(cells),
              "    we.SaveTerrains()", FOOTER]
    return "\n".join(lines)


def screenshot(map_dir: str, shots: Sequence[Tuple[str, Tuple[float, float]]],
               size: Tuple[int, int] = (1280, 720)) -> str:
    """The headless command lines for 3-D verification.

    Returned as a shell snippet, not Python: this runs the editor as a process
    rather than inside it. It must be launched from the data directory (the one
    holding ``pack/`` and ``ymir work/``), and an exe copied to ``D:\\`` needs
    the gran212 import patch.
    """
    out = ["# Run from the data dir (pack/ + ymir work/ present).",
           "# Requires a WorldEditorRemix build; 2D previews need none."]
    for name, (tx, ty) in shots:
        out.append('WorldEditorRemix_MfcRelease.exe --map "%s" --target %d,%d '
                   '--size %d,%d --shot "%s.png" --quit'
                   % (map_dir, int(tx), int(ty), size[0], size[1], name))
    return "\n".join(out)


def write(path, source: str) -> str:
    import pathlib
    p = pathlib.Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(source, encoding="utf-8", newline="\n")
    return str(p)
